# Generated by Django 5.0.6 on 2024-08-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='warning_text',
            new_name='alert_type',
        ),
        migrations.AddField(
            model_name='alert',
            name='date',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
