# Generated by Django 5.0.6 on 2024-08-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_warning_text_alert_alert_type_alert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
