# Generated by Django 5.0.6 on 2024-08-07 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_alert_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
